#!/bin/bash

#
# "**********************************"
# "* UET g++ build tool for student *"
# "* Author: Tran Manh Cuong - K62  *"
# "**********************************"
#

filepath=$1
filename=$(basename "$filepath")
echo
if [ ${#filepath} -eq 0 ]
then
echo "Error: No file input"
else
filebuild="."$filename".uetbuildc++"
g++ $filepath -o $filebuild
runbuild="./"$filebuild
$runbuild
rm $filebuild
fi
echo 
echo "----------------------------------"
echo "Process exited! Done."
