#!/bin/bash

#
# "**********************************"
# "* UET g++ build tool for student *"
# "* Author: Tran Manh Cuong - K62  *"
# "**********************************"
#

filepath=$1
filename=$(basename "$filepath")

if [ ${#filepath} -eq 0 ] then
	echo "Error: No input file"
else
	# Compile the file
	filebuild="."$filename".uetbuildc++"
	g++ -O2 -std=c++11 -s -lm $filepath -o $filebuild
	runbuild="./"$filebuild
	$runbuild
	rm $filebuild
fi
